### ISSUE TITLE
Provide RSS feed

### ISSUE THREAD

**Issue by g-adel** [tromp/tromp.github.io#2]
Hello! Your portfolio of interests are super awesome! Have you considered adding an RSS feed to make it easy for people to follow you?  I'm not sure one already exists but I can't find one. Cheers!

**Comment by tromp** [comment]
My post https://tromp.github.io/blog/2023/11/20/blog-launched
mentions the feed at http://tromp.github.io/blog/atom.xml
Does that work for you?

**Comment by g-adel** [comment]
It certainly does! Thanks :D
You might wanna consider adding a link to it at the bottom of your webpage for easy discoverability.

**Comment by tromp** [comment]
Like so?

**Comment by g-adel** [comment]
Yup, that's perfect!
